---
title: "FAQ"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

## Why am I here?

You are here because you're a student in CI670 - Biostatistics with Computing.
You want to learn about biostatistics and how to use R to perform exploratory 
data analysis and statistical analysis on your data.

## How do I get help?

For course content, email me or your instructor.

But, the most important thing we can teach you is how to find your own answers.
Some resources: [Stackoverflow](https://www.stackoverflow.com)
in RStudio, cheatsheets - go to Help and then cheatsheets or go to the 
[RStudio website](https://www.rstudio.com/resources/cheatsheets/).

## Why are you obsessed with R?

We try to be agnostic about our statistical software.  After all, it's a just a
means to an end.  BUT, R has some pros that we like.

- [R is growing in popularity](http://r4stats.com/articles/popularity/)

- [open science](https://ropensci.org/about/)

- reproducibility

- free

- nice, relatively painless graphics

- free (as in beer)

- active development of new packages, sometimes by experts

## How did you make this awesome website?

This site is hosted by [GitHub Pages](https://pages.github.com), which hosts
content directly from your [GitHub](https://www.github.com)  repository.

We wrote our content in R Markdown and pushed it to our personal repository.
From there, GitHub Pages grabs the html file and puts it out on the internet.